version: "3.8"

services:
  app:
    image: apptica:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE_NAME=apptica
      - API_ENDPOINT=https://api.apptica.com/package/top_history
      - API_TOKEN=fVN5Q9KVOlOHDx9mOsKPAQsFBlEhBOwguLkNEDTZvKzJzT3l
    ports:
      - 80:8080
      - 9000:9000
    depends_on:
      - db

  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=apptica
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d
